// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqzFdrA3Aik6Du5w5aE2L3RETjzE8X3UM',
    appId: '1:561518153507:web:a3d797e486ea7b6a85c696',
    messagingSenderId: '561518153507',
    projectId: 'app-expense',
    authDomain: 'app-expense.firebaseapp.com',
    storageBucket: 'app-expense.appspot.com',
    measurementId: 'G-J0T6LY5748',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCszdUm3uOj9BzbijSoqw_n0-ou-RG9llE',
    appId: '1:561518153507:android:30682234e4c0be5885c696',
    messagingSenderId: '561518153507',
    projectId: 'app-expense',
    storageBucket: 'app-expense.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7IR_0mPlUUaFzCPi_sBPQkcp4Xyy1sWM',
    appId: '1:561518153507:ios:9fe3fd3569cb432e85c696',
    messagingSenderId: '561518153507',
    projectId: 'app-expense',
    storageBucket: 'app-expense.appspot.com',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7IR_0mPlUUaFzCPi_sBPQkcp4Xyy1sWM',
    appId: '1:561518153507:ios:9fe3fd3569cb432e85c696',
    messagingSenderId: '561518153507',
    projectId: 'app-expense',
    storageBucket: 'app-expense.appspot.com',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqzFdrA3Aik6Du5w5aE2L3RETjzE8X3UM',
    appId: '1:561518153507:web:a3ac93e3a49f185185c696',
    messagingSenderId: '561518153507',
    projectId: 'app-expense',
    authDomain: 'app-expense.firebaseapp.com',
    storageBucket: 'app-expense.appspot.com',
    measurementId: 'G-P5S7T8JDK5',
  );
}
